# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcc159b0e1dce914d94f7a742a346f7c1709952462e8e76f2beb3f32043944f826eeda42bc0904ffad179c52806ea89b9e67551073ebda60db4562a837b4530e

test:
  secret_key_base: 34bd2ad0ea95b9cfeaeb4acf81a27bdf7e942e4d227085bfbfd5fe95e3bd9c1274d9a88dd3c01d7aea61570bff072069b3da9218ddcedd6bd3d28405d439097b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
